#!/bin/bash
awk '
/const wastedPotential/ {
    print $0
    print "  "
    print "  // Gamification & OS Metrics"
    print "  const userLevel = Math.floor(currentScore / 20) + 1;"
    print "  const userXP = currentScore * 125;"
    print "  const nextLevelXP = userLevel * 20 * 125;"
    print "  const progressToNextLevel = ((userXP - ((userLevel - 1) * 20 * 125)) / (nextLevelXP - ((userLevel - 1) * 20 * 125))) * 100;"
    print "  "
    print "  const cageScore = Math.min(100, Math.round(currentScore * 1.1));"
    print "  const executionScore = Math.min(100, Math.round(currentScore * 0.9));"
    print "  const momentumScore = Math.min(100, Math.round(currentScore * 1.2));"
    next
}
/\{\/\* 1\. Header Banner & Identity \*\/\}/ {
    print "      {/* Gamification Header Bar */}"
    print "      <div className=\"flex items-center justify-between bg-slate-900 border border-slate-800 rounded-2xl p-4 mb-6\">"
    print "        <div className=\"flex items-center gap-4\">"
    print "          <div className=\"w-12 h-12 rounded-full bg-gradient-to-tr from-violet-600 to-amber-500 p-0.5\">"
    print "            <div className=\"w-full h-full bg-slate-950 rounded-full flex items-center justify-center font-black text-white\">"
    print "              L{userLevel}"
    print "            </div>"
    print "          </div>"
    print "          <div>"
    print "            <div className=\"flex items-center gap-2\">"
    print "              <h3 className=\"font-bold text-white\">{userName}</h3>"
    print "              <span className=\"px-2 py-0.5 rounded text-[10px] font-bold bg-violet-500/20 text-violet-400 border border-violet-500/30 uppercase\">"
    print "                {currentScore >= 80 ? \"Expert\" : currentScore >= 50 ? \"Creator\" : \"Iniciante\"}"
    print "              </span>"
    print "            </div>"
    print "            <div className=\"flex items-center gap-3 mt-1\">"
    print "              <div className=\"w-32 h-1.5 bg-slate-800 rounded-full overflow-hidden\">"
    print "                <motion.div initial={{ width: 0 }} animate={{ width: `${progressToNextLevel}%` }} transition={{ duration: 1 }} className=\"h-full bg-violet-500\" />"
    print "              </div>"
    print "              <span className=\"text-[10px] text-slate-400 font-mono\">{userXP} / {nextLevelXP} XP</span>"
    print "            </div>"
    print "          </div>"
    print "        </div>"
    print "        <div className=\"hidden md:flex items-center gap-6\">"
    print "          <div className=\"text-center\">"
    print "            <span className=\"block text-[10px] text-slate-500 uppercase tracking-wider font-bold mb-1\">Sequência</span>"
    print "            <span className=\"text-white font-mono font-bold flex items-center gap-1\"><Zap size={14} className=\"text-amber-400\" /> 1 Dia</span>"
    print "          </div>"
    print "          <div className=\"text-center\">"
    print "            <span className=\"block text-[10px] text-slate-500 uppercase tracking-wider font-bold mb-1\">Conquistas</span>"
    print "            <span className=\"text-white font-mono font-bold flex items-center gap-1\"><Target size={14} className=\"text-emerald-400\" /> 2/15</span>"
    print "          </div>"
    print "        </div>"
    print "      </div>"
    print ""
    print $0
    next
}
/\{\/\* 2\.5 The 5 Strategic Pillars \*\/\}/ {
    print "      {/* Sub-Scores Panel (CAGE, Execution, Momentum) */}"
    print "      <div className=\"grid grid-cols-1 md:grid-cols-3 gap-5 pt-4\">"
    print "        <div className=\"bg-slate-900 border border-slate-800 rounded-2xl p-5 flex items-center gap-4\">"
    print "          <div className=\"w-14 h-14 rounded-full border-[4px] border-indigo-500/20 flex items-center justify-center relative\">"
    print "            <svg className=\"absolute inset-0 w-full h-full transform -rotate-90\">"
    print "              <circle cx=\"24\" cy=\"24\" r=\"22\" className=\"stroke-indigo-500\" strokeWidth=\"4\" fill=\"none\" strokeDasharray={`${cageScore * 1.38} 138`} />"
    print "            </svg>"
    print "            <span className=\"font-bold text-slate-200 text-sm\">{cageScore}</span>"
    print "          </div>"
    print "          <div>"
    print "            <h4 className=\"font-bold text-white text-sm\">C.A.G.E Score</h4>"
    print "            <p className=\"text-[10px] text-slate-400 leading-tight mt-0.5\">Capacidade de retenção e conversão orgânica</p>"
    print "          </div>"
    print "        </div>"
    print "        <div className=\"bg-slate-900 border border-slate-800 rounded-2xl p-5 flex items-center gap-4\">"
    print "          <div className=\"w-14 h-14 rounded-full border-[4px] border-emerald-500/20 flex items-center justify-center relative\">"
    print "            <svg className=\"absolute inset-0 w-full h-full transform -rotate-90\">"
    print "              <circle cx=\"24\" cy=\"24\" r=\"22\" className=\"stroke-emerald-500\" strokeWidth=\"4\" fill=\"none\" strokeDasharray={`${executionScore * 1.38} 138`} />"
    print "            </svg>"
    print "            <span className=\"font-bold text-slate-200 text-sm\">{executionScore}</span>"
    print "          </div>"
    print "          <div>"
    print "            <h4 className=\"font-bold text-white text-sm\">Execution Score</h4>"
    print "            <p className=\"text-[10px] text-slate-400 leading-tight mt-0.5\">Disciplina e consistência nas ações recomendadas</p>"
    print "          </div>"
    print "        </div>"
    print "        <div className=\"bg-slate-900 border border-slate-800 rounded-2xl p-5 flex items-center gap-4\">"
    print "          <div className=\"w-14 h-14 rounded-full border-[4px] border-amber-500/20 flex items-center justify-center relative\">"
    print "            <svg className=\"absolute inset-0 w-full h-full transform -rotate-90\">"
    print "              <circle cx=\"24\" cy=\"24\" r=\"22\" className=\"stroke-amber-500\" strokeWidth=\"4\" fill=\"none\" strokeDasharray={`${momentumScore * 1.38} 138`} />"
    print "            </svg>"
    print "            <span className=\"font-bold text-slate-200 text-sm\">{momentumScore}</span>"
    print "          </div>"
    print "          <div>"
    print "            <h4 className=\"font-bold text-white text-sm\">Momentum Score</h4>"
    print "            <p className=\"text-[10px] text-slate-400 leading-tight mt-0.5\">Velocidade de crescimento atual vs potencial</p>"
    print "          </div>"
    print "        </div>"
    print "      </div>"
    print ""
    print $0
    next
}
{ print $0 }
' src/components/ResultView.tsx > src/components/ResultView.tsx.tmp && mv src/components/ResultView.tsx.tmp src/components/ResultView.tsx
